name: pre-commit-disabled
on:
  workflow_dispatch:
jobs:
  pre-commit:
    if: false
    runs-on: ubuntu-latest
    env:
      GIT_LFS_SKIP_SMUDGE: true
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v3
      - uses: pre-commit/action@v3.0.1
